name: Git Actions CI/CD Pipeline

on:
  push:   
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2
      - name: Read hello.txt
        run: cat hello.txt

  build_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'