name: Git Actions CI/CD Pipeline

on:
  push:   
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test_job      
      runs-on: ubuntu-latest
     -name: Git Clone
      uses: actions/checkout@v2

      -name: Read hello.txt
       run: cat hello.txt