name: Git Actions CI/CD Pipeline

on:
  push:   
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  read_hello_file:       
      runs-on: ubuntu-latest
      -name: Git Clone
      -uses: actions/checkout@v2

      name: Read hello.txt
      run: cat hello.txt